/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'napi-demo.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./napi-demo.android-arm64.node')
          } else {
            nativeBinding = require('napi-demo-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'napi-demo.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./napi-demo.android-arm-eabi.node')
          } else {
            nativeBinding = require('napi-demo-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'napi-demo.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./napi-demo.win32-x64-msvc.node')
          } else {
            nativeBinding = require('napi-demo-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'napi-demo.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./napi-demo.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('napi-demo-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'napi-demo.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./napi-demo.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('napi-demo-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'napi-demo.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./napi-demo.darwin-universal.node')
      } else {
        nativeBinding = require('napi-demo-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'napi-demo.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./napi-demo.darwin-x64.node')
          } else {
            nativeBinding = require('napi-demo-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'napi-demo.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./napi-demo.darwin-arm64.node')
          } else {
            nativeBinding = require('napi-demo-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'napi-demo.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./napi-demo.freebsd-x64.node')
      } else {
        nativeBinding = require('napi-demo-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'napi-demo.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./napi-demo.linux-x64-musl.node')
            } else {
              nativeBinding = require('napi-demo-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'napi-demo.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./napi-demo.linux-x64-gnu.node')
            } else {
              nativeBinding = require('napi-demo-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'napi-demo.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./napi-demo.linux-arm64-musl.node')
            } else {
              nativeBinding = require('napi-demo-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'napi-demo.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./napi-demo.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('napi-demo-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        localFileExisted = existsSync(
          join(__dirname, 'napi-demo.linux-arm-gnueabihf.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./napi-demo.linux-arm-gnueabihf.node')
          } else {
            nativeBinding = require('napi-demo-linux-arm-gnueabihf')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { DEFAULT_COST, sum, Animal, Kind, coolFunction, getUndefined, log, getNull, getEnv, read, read2, isGood, keys, createObj, logPackageName, readPackageJson, arrLen, getTupleArray, vecLen, getNums, convertU32Array, createExternalTypedArray, mutateTypedArray, PathData, callThreadsafeFunction2, callThreadsafeFunction, callLongThreadsafeFunction, threadsafeFunctionThrowError, threadsafeFunctionFatalMode, threadsafeFunctionFatalModeError, threadsafeFunctionClosureCapture, tsfnCallWithCallback, tsfnAsyncCall, acceptThreadsafeFunction, acceptThreadsafeFunctionFatal, acceptThreadsafeFunctionTupleArgs, tsfnReturnPromise, tsfnReturnPromiseTimeout, tsfnThrowFromJs, runScript } = nativeBinding

module.exports.sum = sum
module.exports.DEFAULT_COST = DEFAULT_COST
module.exports.Animal = Animal
module.exports.Kind = Kind
module.exports.coolFunction = coolFunction
module.exports.getUndefined = getUndefined
module.exports.log = log
module.exports.getNull = getNull
module.exports.getEnv = getEnv
module.exports.read = read
module.exports.read2 = read2
module.exports.isGood = isGood
module.exports.keys = keys
module.exports.createObj = createObj
module.exports.logPackageName = logPackageName
module.exports.readPackageJson = readPackageJson
module.exports.arrLen = arrLen
module.exports.getTupleArray = getTupleArray
module.exports.vecLen = vecLen
module.exports.getNums = getNums
module.exports.convertU32Array = convertU32Array
module.exports.createExternalTypedArray = createExternalTypedArray
module.exports.mutateTypedArray = mutateTypedArray
module.exports.PathData = PathData
module.exports.callThreadsafeFunction2 = callThreadsafeFunction2
module.exports.callThreadsafeFunction = callThreadsafeFunction
module.exports.callLongThreadsafeFunction = callLongThreadsafeFunction
module.exports.threadsafeFunctionThrowError = threadsafeFunctionThrowError
module.exports.threadsafeFunctionFatalMode = threadsafeFunctionFatalMode
module.exports.threadsafeFunctionFatalModeError = threadsafeFunctionFatalModeError
module.exports.threadsafeFunctionClosureCapture = threadsafeFunctionClosureCapture
module.exports.tsfnCallWithCallback = tsfnCallWithCallback
module.exports.tsfnAsyncCall = tsfnAsyncCall
module.exports.acceptThreadsafeFunction = acceptThreadsafeFunction
module.exports.acceptThreadsafeFunctionFatal = acceptThreadsafeFunctionFatal
module.exports.acceptThreadsafeFunctionTupleArgs = acceptThreadsafeFunctionTupleArgs
module.exports.tsfnReturnPromise = tsfnReturnPromise
module.exports.tsfnReturnPromiseTimeout = tsfnReturnPromiseTimeout
module.exports.tsfnThrowFromJs = tsfnThrowFromJs
module.exports.runScript = runScript
